function [Ndat] = importfileData(fileToRead1)
%IMPORTFILE1(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 03-Apr-2009 01:20:14

% Import the file
rawData1 = importdata(fileToRead1);

[unused,name] = fileparts(fileToRead1); 
newData1.(genvarname(name)) = rawData1;

vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

%BELOW ADDED BY KEVIN KING
%Store the data in a return variable so this function can pass to external
%   variables
Ndat = newData1.(genvarname(name));
