%AngleDiff will generate two matrices for Odd and Even with all six adjacent
%angle differences for each component of Odd and Even matrices. 
function [OddAngle,EvenAngle]=AngleDiff(Odd,Even)
%Input:
%Odd, Even: two cell arrays generated by TwoMatrix.m, separating the point
%           data into two different matrices so that it is eaiser to find the angle
%           difference.
%OddAngle, EvenAngle:two cell arrays representing the six different angle misorientation corresponding to 
%                       position in Odd and Even matrix. each component
%                       represents the six angle misorientation between the
%                       center pixel and its adjacent hexagon pixels.

%OddA and OddB are the dimensions of Odd Matrix, EvenA and EvenB are the
%dimensions of the Even matrix.
[OddA,OddB]=size(Odd);
[EvenA,EvenB]=size(Even);

%Initializing OddAngle and EvenAngle Cell Arrays.
OddAngle=cell(OddA,OddB);
EvenAngle=cell(EvenA,EvenB);

for i = 1: OddA
    i;
    for j=1: OddB
        odd = zeros(1,6);
        Euler = Odd{i,j}(:,1:3);
        angle1 = ipfplotter(Euler(1),Euler(2),Euler(3));
        if j+1<=OddB % right of the current cell.
            odd(1)=misorientation(angle1,Odd{i,j+1}(:,1:3));
        else
            odd(1)=0;
        end
        
        if i<=EvenA && j<=EvenB % bottom right of the current cell(in Even Matrix)
            odd(2)=misorientation(angle1,Even{i,j}(:,1:3));
        else
            odd(2)=0;
        end
        
        if i<=EvenA && j-1>0 && j-1<=EvenB % bottom left of the current cell(in Even Matrix)
            odd(3)=misorientation(angle1,Even{i,j-1}(:,1:3));
        else
            odd(3)=0;
        end
        
        if j-1>0
            odd(4)=misorientation(angle1,Odd{i,j-1}(:,1:3)); % left of the current cell
        else 
            odd(4)=0; %it is zero if there is no cell to the left. 
        end
        
        if i-1>0 && i-1<=EvenA && j<=EvenB % top left of the current cell(in Even Matrix) 
            odd(6)=misorientation(angle1,Even{i-1,j}(:,1:3));
        else
            odd(6)=0;
        end
        
        if i-1>0 && i-1<=EvenA && j-1>0 && j-1 <=EvenB % top right of the current cell(in Even Matrix)
            odd(5)=misorientation(angle1,Even{i-1,j-1}(:,1:3));
        else
            odd(5)=0;
        end
        OddAngle{i,j} = odd;
    end
end

%similar procedures goes on in one cell of the Odd Matrix
for i = 1: EvenA
    for j=1: EvenB
        even = zeros(1,6);
        Euler = Even{i,j}(:,1:3);
        angle1 = ipfplotter(Euler(1),Euler(2),Euler(3));
        if j+1<=EvenB% right of the current cell
            even(1)=misorientation(angle1,Even{i,j+1}(:,1:3));
        else
            even(1)=0;
        end
        
        if i+1<=OddA &&j+1 <=OddB% bottom right of the current cell
            even(2)=misorientation(angle1,Odd{i+1,j+1}(:,1:3));
        else
            even(2)=0;
        end
        
        if i+1<=OddA && j<=OddB% bottom left of the current cell
            even(3)=misorientation(angle1,Odd{i+1,j}(:,1:3));
        else
            even(3)=0;
        end
        
        if j-1>0 % left of the current cell
            even(4)=misorientation(angle1,Even{i,j-1}(:,1:3));
        else 
            even(4)=0;
        end
        
        if i<=OddA && j<=OddB % top left of the current cell
            even(5)=misorientation(angle1,Odd{i,j}(:,1:3));
        else
            even(5)=0;
        end
        
        if i<=OddA && j+1<=OddB% top right of the current cell
            even(6)=misorientation(angle1,Odd{i,j+1}(:,1:3));
        else
            even(6)=0;
        end
        EvenAngle{i,j}=even;
        
    end
end


