%boundary1 gives the matrix of positions specifying the boundary within the
%range of lower and upper bounds.
function [Bound, Values]=boundary1(Odd,Even,OddAngle,EvenAngle,lower,upper)
%Input:
% Odd and Even are cell arrays generated by TwoMatrix.m
%OddAngle and EvenAngle are cell arrays generated by AngleDiff.m
%lower: lower threshhold value in degree
%upper: upper threshhold value in degree

%size of Odd and Even Cell Arrays. Initialization of Boundary Matrix.
[OddA,OddB]=size(Odd)
[EvenA,EvenB]=size(Even)
Bound=[];
Value=zeros(numel(Odd) + numel(Even), 1);
row=zeros(numel(Odd) + numel(Even), 1);
index=zeros(numel(Odd) + numel(Even), 1);
for i=1:OddA
    for j=1:OddB
        val = 0;
        for q=1:6 % number 1 to 6 correspond the order the angle was stored in AngleDiff.m
            if OddAngle{i,j}(q)<=upper && OddAngle{i,j}(q)>=lower
                if q==1 && (j-1>0)
                    Bound=[Bound(:,:);Odd{i,j-1}(:,4:5)];
                    val = val +1;
                end
                
                if q==2 && (j+1<=OddB)
                    Bound=[Bound(:,:);Odd{i,j+1}(:,4:5)];
                    val = val +2;
                end
                
                if q==3 && (i<=EvenA) && (j<=EvenB)
                    Bound=[Bound(:,:);Even{i,j}(:,4:5)];
                    val = val +4;
                end
                
                if q==4 && i<=EvenA && (j-1>0) && (j-1<=EvenB)
                    Bound=[Bound(:,:);Even{i,j-1}(:,4:5)];
                    val=val+8;
                end
                
                if q==5 && (i-1>0) && (i-1<=EvenA) && (j<=EvenB)
                    Bound=[Bound(:,:);Even{i-1,j}(:,4:5)];
                    val = val +16;
                end
                
                if q==6 && (i-1>0) && (i-1<=EvenA) && (j-1>0) && (j-1 <=EvenB)
                    Bound=[Bound(:,:);Even{i-1,j-1}(:,4:5)];
                    val = val +32;
                end
            end
        end
        Value((i-1)*(EvenB+OddB)+j) = val;
        index((i-1)*(EvenB+OddB)+j) = j*2-1;
        row((i-1)*(EvenB+OddB)+j)   = i*2-1;
    end
end

for i=1:EvenA
    for j=1:EvenB
        val = 0;
        for q=1:6
            if EvenAngle{i,j}(q)<=upper && EvenAngle{i,j}(q)>=lower
                if q==1 && (j-1>0)
                    Bound=[Bound(:,:);Even{i,j-1}(:,4:5)];
                    val = val+1;
                end
                
                if q==2 && (j+1<=EvenB)
                    Bound=[Bound(:,:);Even{i,j+1}(:,4:5)];
                    val = val +2;
                end
                
                if q==3 && i<=OddA && j<=OddB
                    Bound=[Bound(:,:);Odd{i,j}(:,4:5)];
                    val=val+4;
                end
                
                if q==4 && i<=OddA && (j+1<=OddB)
                    Bound=[Bound(:,:);Odd{i,j+1}(:,4:5)];
                    val=val+8;
                end
                
                if q==5 && (i+1<=OddA) && j<=OddB
                    Bound=[Bound(:,:);Odd{i+1,j}(:,4:5)];
                    val=val+16;
                end
                
                if q==6 && (i+1<=OddA) && (j+1 <=OddB)
                    Bound=[Bound(:,:);Odd{i+1,j+1}(:,4:5)];
                    val=val+32;
                end
            end
        end
        Value((i-1)*(EvenB+OddB)+j+EvenB) = val;
        index((i-1)*(EvenB+OddB)+j+EvenB) = j*2;
        row((i-1)*(EvenB+OddB)+j+EvenB)   = i*2;
    end
end

Values = [Value, index, row];